apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql:
    CREATE DATABASE authdb;
    CREATE DATABASE orderdb;
    GRANT ALL PRIVILEGES ON DATABASE authdb TO admin;
    GRANT ALL PRIVILEGES ON DATABASE orderdb TO admin;